site_name: Peppy
site_url: http://code.databio.org/peppy/
repo_url: http://github.com/pepkit/peppy
pypi_name: peppy

nav:
  - Getting started:
    - Introduction: README.md
    - Installing and Hello World: hello-world.md
  - How-to Guides:
    - How to use peppy: tutorial.md
    - How to use subsample table: feature4_subsample_table.md
    - How to use amendments: feature5_amend.md
    - How to use append sample modifier: feature1_append.md
    - How to use imply sample modifier: feature2_imply.md
  - Reference:
    - API: autodoc_build/peppy.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      autodoc_package: "peppy"
      no_top_level: true
  - search
